// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69PjLqZv_-VM9KG-P0zY7cwr4DB_uwro',
    appId: '1:341197800342:web:d7e90204f364186d6c53b7',
    messagingSenderId: '341197800342',
    projectId: 'busproject-fa621',
    authDomain: 'busproject-fa621.firebaseapp.com',
    storageBucket: 'busproject-fa621.appspot.com',
    measurementId: 'G-JGB0T9T96W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPDFquMSDX3PDGncqYSExoVQF2xGrxBo',
    appId: '1:341197800342:android:506338c02f66f1196c53b7',
    messagingSenderId: '341197800342',
    projectId: 'busproject-fa621',
    storageBucket: 'busproject-fa621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6V08v1ftlvsgwl2N5ph6lC_dLZ92sCU',
    appId: '1:341197800342:ios:3dd0b8c00f4663c96c53b7',
    messagingSenderId: '341197800342',
    projectId: 'busproject-fa621',
    storageBucket: 'busproject-fa621.appspot.com',
    iosClientId: '341197800342-ufqd7g46ofbr4iguv35jt2kjuirje1kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6V08v1ftlvsgwl2N5ph6lC_dLZ92sCU',
    appId: '1:341197800342:ios:77899bbb75d3dbb76c53b7',
    messagingSenderId: '341197800342',
    projectId: 'busproject-fa621',
    storageBucket: 'busproject-fa621.appspot.com',
    iosClientId: '341197800342-tbej3aivcsiv6rg069pck008l4n9gbco.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTestapp.RunnerTests',
  );
}
